apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: bandzior/nginx-static
      context: site
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'nginx/default.conf'
            dest: '/etc/nginx/conf.d/'
