apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-ssl-prod
spec:
  secretName: web-ssl-prod
  issuerRef:
    name: lets-encrypt-prod
    kind: ClusterIssuer
  commonName: site.balcerski.eu
  dnsNames:
    - site.balcerski.eu
