apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 'bandziorgit@gmail.com'
    privateKeySecretRef:
      name: lets-encrypt-staging
    solvers:
      - http01:
          ingress:
            name: ingress-srv
