apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-tls
spec:
  secretName: web-ssl-staging
  issuerRef:
    name: lets-encrypt-staging
    kind: ClusterIssuer
  commonName: site-balcerski-eu
  dnsNames:
    - site.balcerski.eu
