apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-ssl-staging
spec:
  secretName: web-ssl-staging
  issuerRef:
    name: lets-encrypt-staging
    kind: ClusterIssuer
  commonName: cert-staging
  dnsNames:
    - site.balcerski.eu
