apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
spec:
  secretName: site-balcerski-eu
  issuerRef:
    name: lets-encrypt-test
    kind: ClusterIssuer
  commonName: site-balcerski-eu
  dnsNames:
    - site.balcerski.eu
