# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE when there is a push to the "master" branch.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Create and configure a Workload Identity Provider for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
#
# 3. Change the values for the GAR_LOCATION, GKE_ZONE, GKE_CLUSTER, IMAGE, REPOSITORY and DEPLOYMENT_NAME environment variables (below).
#
# For more support on how to run the workflow, please visit https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/gke-kustomize

name: Build and Deploy to GKE

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: europe-central2-a # TODO: update region of the Artifact Registry
  GKE_CLUSTER: jubicular-cluster    # TODO: update to cluster name
  GKE_ZONE: europe-central2-a    # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-jubicular-depl # TODO: update to deployment name
  REPOSITORY: bandzior # TODO: update to Artifact Registry docker repository
  IMAGE: nginx
  SHA: $(git rev-parse HEAD)

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
        

    # Authentication via credentials json
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set Project
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        # Get the GKE credentials so we can deploy to the cluster
        
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}


    - name: Docker configuration
      run: |-
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Configure Docker authentication for cloud
      run: |-
        gcloud --quiet auth configure-docker
    
    - name: Build Docker image
      run: |-
        docker build -t bandzior/site-k8s:latest -t bandzior/site-k8s:${{ env.SHA }} -f ./site/Dockerfile ./site
    
    - name: Push Docker image
      run: |-
        docker push bandzior/site-k8s:latest

        docker push bandzior/site-k8s:${{ env.SHA }}

    - name: Kubectl Apply
      run: |-
        kubectl apply -f infra/k8s
    

